#!/usr/bin/python

# Third party libraries
from rich import print as rprint
from rich.traceback import install

# Internal library
from lib.ai import commands as ai_commands
from lib.ai.arguments import argument_parser
from lib.ai.print import print_line, print_title, print_verbose_details
from lib.ai.session import interactive_session, passive_session, finish_reason_check
from lib.ai.user_input import initial_message
from lib.config import save_config, load_config
from lib.desktop.clipboard import send_to_clipboard
from lib.openai import models

# This install function from 'rich' adds syntax highlighting to exceptions
install()

models.assert_openai_api_key()
flags, commands, parameters = argument_parser()

if flags['debug']:
    rprint(f'flags: {flags}')
    rprint(f'commands: {commands}')
    rprint(f'parameters: {parameters}')

if commands['list']:
    ai_commands.list(commands['list'])
if commands['edit']:
    ai_commands.edit(commands['edit'])

config = load_config()
messages = list()

model_list = [m['name'] for m in models.filter_models('gpt')]
if not config.get('model') or not config['model'] in model_list or flags['change_model']:
    config['model'] = models.choose_model(config.get('model'))
    save_config(config)
model_name = config['model']

prompt_name, prompt = ai_commands.prompt(commands['prompt'])
if prompt:
    messages.append({'role': 'user', 'content': prompt})
    messages.append({'role': 'assistant', 'content': 'Understood'})

file_content = ai_commands.file(commands['file'])
if file_content:
    messages.append({'role': 'user', 'content': file_content})
    messages.append({'role': 'assistant', 'content': 'How can I assist you?'})

if not commands['query'] and not flags['interactive']:
    while not commands['query']:
        commands['query'] = initial_message()

if commands['query']:
    messages.append({'role': 'user', 'content': commands['query']})

if flags['interactive']:
    if flags['verbose']:
        print_verbose_details(model_name, messages, flags,
                              commands, parameters, prompt_name, None)
    interactive_session(model_name, messages, flags, commands, parameters)

if flags['debug']:
    rprint(f'messages: {messages}')

print_title(model_name, to_stderr=True)

session_data = passive_session(
    model_name, messages, flags, commands, parameters)

finish_reason_check(session_data['finish_reason'])

if flags['verbose']:
    print_title(model_name)
    print_verbose_details(model_name, messages, flags, commands,
                          parameters, prompt_name, session_data['tokens'])

send_to_clipboard(session_data['content'])
if flags['synchronous'] or flags['verbose']:
    print(session_data['content'])
